language: ruby
rvm:
  - 2.4.1
bundler_args: --without production

services:
  - postgresql

before_script:
  - psql -c 'create database ZagakuAppRails_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
