# Env variable linked through pusher.rb

GOOGLE_CLIENT_ID:  ""
GOOGLE_CLIENT_SECRET: ""
GOOGLE_ICAL_LINK: ""
GITHUB_CLIENT_ID: ""
GITHUB_CLIENT_SECRET: ""
GITHUB_REPO: ""
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
